"""End-to-end integration tests: blueprint → classify → generate → audit → approve.

These tests verify the full Arquitecto v2 pipeline with:
- Real ProjectComplexityClassifier (no mock)
- Real ContractAuditor with all 6 validators (no mock)
- Mocked Architect driver (avoids real API calls)

The goal is to verify that the components connect correctly and that a
well-formed contract generated by the Architect passes the full audit.
"""
import asyncio
import json
from dataclasses import dataclass, field
from typing import Optional
from unittest.mock import AsyncMock, MagicMock

import pytest

from kernel.intelligence.architect import Architect
from kernel.intelligence.complexity_classifier import (
    ComplexityLevel,
    ProjectComplexityClassifier,
)
from kernel.intelligence.contract_schemas import MasterContract
from kernel.integrity.contract_auditor import ContractAuditor
from kernel.orchestration.contract_refinement_loop import (
    ContractRefinementLoop,
)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def run(coro):
    return asyncio.get_event_loop().run_until_complete(coro)


@dataclass
class FakeDriverResponse:
    content: str
    error_code: Optional[str] = None
    tokens_input: int = 500
    tokens_output: int = 1000
    latency_ms: int = 800
    model_used: str = "claude-haiku-4-5-20251001"
    cost_usd: float = 0.03
    metadata: dict = field(default_factory=dict)


def _make_driver(contract_json: str):
    driver = MagicMock()
    driver.call = AsyncMock(return_value=FakeDriverResponse(content=contract_json))
    return driver


def _simple_contract_json(project_id="proj_simple") -> str:
    return json.dumps({
        "project_id": project_id,
        "project_name": "Todo App",
        "version": "1.0.0",
        "complexity_level": "simple",
        "model_used": "claude-haiku-4-5-20251001",
        "modules": [
            {
                "id": "task_service",
                "name": "Task Service",
                "purpose": "Manages creation, retrieval, updating, and deletion of user tasks",
                "interfaces": [{
                    "name": "TaskServiceInterface",
                    "description": "Public interface for task CRUD operations",
                    "methods": [
                        {
                            "name": "create_task",
                            "parameters": {"title": "str", "description": "str"},
                            "returns": "TaskRecord",
                            "description": "Creates a new task and persists it to the database",
                            "example_usage": "service.create_task('Buy milk', 'Get 2 liters')",
                        },
                        {
                            "name": "get_task",
                            "parameters": {"task_id": "str"},
                            "returns": "TaskRecord",
                            "description": "Retrieves an existing task by its unique identifier",
                            "example_usage": "service.get_task('task-abc-123')",
                        },
                        {
                            "name": "list_tasks",
                            "parameters": {},
                            "returns": "list[TaskRecord]",
                            "description": "Returns all tasks for the current user sorted by creation date",
                            "example_usage": "service.list_tasks()",
                        },
                        {
                            "name": "delete_task",
                            "parameters": {"task_id": "str"},
                            "returns": "bool",
                            "description": "Deletes a task by ID and returns True if successful",
                            "example_usage": "service.delete_task('task-abc-123')",
                        },
                    ],
                }],
                "goal_ids": ["goal_task_management"],
                "layer": "application",
            },
            {
                "id": "persistence_service",
                "name": "Persistence Service",
                "purpose": "Handles all database read and write operations for task data",
                "interfaces": [{
                    "name": "PersistenceInterface",
                    "description": "Low-level storage operations",
                    "methods": [{
                        "name": "save",
                        "parameters": {"record": "TaskRecord"},
                        "returns": "str",
                        "description": "Persists a task record and returns its assigned ID",
                        "example_usage": "db.save(task_record)",
                    }],
                }],
                "goal_ids": ["goal_data_storage"],
                "layer": "infrastructure",
                "depends_on": [],
            },
        ],
        "data_types": [
            {
                "name": "TaskRecord",
                "kind": "object",
                "fields": {"id": "str", "title": "str", "description": "str", "done": "bool"},
                "description": "Represents a single task in the system with its status and metadata",
                "used_by_modules": ["task_service", "persistence_service"],
            }
        ],
        "event_channels": [
            {
                "name": "task.created",
                "payload_schema": "TaskRecord",
                "publishers": ["task_service"],
                "subscribers": [],
                "description": "Fired when a new task is successfully created",
            }
        ],
        "extension_points": [
            {
                "id": "ext_auth_middleware",
                "type": "middleware_slot",
                "location": "HTTP request pipeline before route handlers",
                "contract": "Must implement process(request) -> response and remain stateless across calls",
                "description": "Slot for authentication and authorization middleware",
                "example_use_case": "Add JWT validation before every API endpoint",
            },
            {
                "id": "ext_task_metadata",
                "type": "metadata_field",
                "location": "TaskRecord entity in persistence layer",
                "contract": "Must be a JSON-serializable dict with string keys and primitive values only",
                "description": "Extensible metadata field on TaskRecord for custom attributes",
                "example_use_case": "Store custom tags or priority labels per task",
            },
            {
                "id": "ext_notification_channel",
                "type": "event_channel",
                "location": "Event bus, reserved for future integrations",
                "contract": "Must follow CloudEvents spec with source, type, and subject fields required",
                "description": "Reserved event channel for future notification integrations",
                "example_use_case": "Send push notifications when tasks are completed",
            },
        ],
        "error_types": [
            {
                "name": "TaskNotFoundError",
                "code": "TASK_NOT_FOUND",
                "message_template": "Task with id '{task_id}' was not found",
                "recoverable": False,
                "http_status": 404,
                "raised_by_modules": ["task_service"],
            },
            {
                "name": "TaskValidationError",
                "code": "TASK_VALIDATION_FAILED",
                "message_template": "Task validation failed: {reason}",
                "recoverable": True,
                "http_status": 422,
                "raised_by_modules": ["task_service"],
            },
            {
                "name": "StorageError",
                "code": "STORAGE_UNAVAILABLE",
                "message_template": "Storage service unavailable: {detail}",
                "recoverable": True,
                "http_status": 503,
                "raised_by_modules": ["persistence_service"],
            },
        ],
        "constants": [
            {
                "name": "MAX_TASK_TITLE_LENGTH",
                "value": "200",
                "type": "int",
                "description": "Maximum allowed length for a task title in characters",
                "used_in_modules": ["task_service"],
            }
        ],
        "architectural_decisions": [
            {
                "id": "adr_001",
                "title": "Separate persistence from business logic",
                "context": "Task management requires both business rules and data storage",
                "decision": "Use a dedicated persistence_service to isolate storage concerns",
                "consequences": ["Easier to swap storage backends", "Slightly more indirection"],
                "alternatives_considered": ["Single service with embedded DB calls"],
            }
        ],
        "assumptions": [
            "Single user per deployment — no multi-tenancy required",
            "SQLite is sufficient for the expected data volume",
        ],
        "metadata": {},
    })


def _medium_contract_json(project_id="proj_medium") -> str:
    """A medium-complexity e-commerce contract for integration testing."""
    return json.dumps({
        "project_id": project_id,
        "project_name": "Simple E-Commerce",
        "version": "1.0.0",
        "complexity_level": "medium",
        "model_used": "claude-sonnet-4-6",
        "modules": [
            {
                "id": "product_catalog",
                "name": "Product Catalog",
                "purpose": "Manages product listings, inventory counts, and catalog search operations",
                "interfaces": [{
                    "name": "CatalogInterface",
                    "description": "Product catalog operations",
                    "methods": [{
                        "name": "search_products",
                        "parameters": {"query": "str", "limit": "int"},
                        "returns": "list[Product]",
                        "description": "Searches products by keyword and returns paginated results",
                        "example_usage": "catalog.search_products('shirt', 10)",
                    }],
                }],
                "goal_ids": ["goal_catalog"],
                "layer": "domain",
            },
            {
                "id": "order_service",
                "name": "Order Service",
                "purpose": "Handles order lifecycle from cart creation through payment confirmation",
                "interfaces": [{
                    "name": "OrderInterface",
                    "description": "Order management operations",
                    "methods": [{
                        "name": "create_order",
                        "parameters": {"cart_id": "str", "user_id": "str"},
                        "returns": "Order",
                        "description": "Creates a new order from a cart and initiates payment flow",
                        "example_usage": "orders.create_order('cart-123', 'user-456')",
                    }],
                }],
                "goal_ids": ["goal_checkout"],
                "layer": "application",
                "depends_on": ["product_catalog"],
            },
            {
                "id": "payment_gateway",
                "name": "Payment Gateway",
                "purpose": "Integrates with Stripe to process payments and manage refunds securely",
                "interfaces": [{
                    "name": "PaymentInterface",
                    "description": "Payment processing operations",
                    "methods": [{
                        "name": "charge",
                        "parameters": {"amount": "int", "token": "str"},
                        "returns": "str",
                        "description": "Charges the given amount using the Stripe payment token",
                        "example_usage": "gateway.charge(1000, 'tok_visa')",
                    }],
                }],
                "goal_ids": ["goal_payments"],
                "layer": "infrastructure",
            },
        ],
        "data_types": [
            {
                "name": "Product",
                "kind": "object",
                "fields": {"id": "str", "name": "str", "price": "int", "stock": "int"},
                "description": "Represents a sellable product with its price and available inventory",
                "used_by_modules": ["product_catalog", "order_service"],
            },
            {
                "name": "Order",
                "kind": "object",
                "fields": {"id": "str", "user_id": "str", "total": "int", "status": "str"},
                "description": "Represents a customer order with its current lifecycle status and total",
                "used_by_modules": ["order_service"],
            },
        ],
        "event_channels": [
            {
                "name": "order.created",
                "payload_schema": "Order",
                "publishers": ["order_service"],
                "subscribers": ["payment_gateway"],
                "description": "Fired when a new order is successfully created and awaiting payment",
            },
            {
                "name": "payment.confirmed",
                "payload_schema": "Order",
                "publishers": ["payment_gateway"],
                "subscribers": ["order_service"],
                "description": "Fired when a payment is confirmed and the order can be fulfilled",
            },
        ],
        "extension_points": [
            {
                "id": "ext_auth_middleware",
                "type": "middleware_slot",
                "location": "HTTP request pipeline",
                "contract": "Must implement process(request) -> response and be stateless across invocations",
                "description": "Authentication middleware slot",
                "example_use_case": "JWT validation",
            },
            {
                "id": "ext_product_metadata",
                "type": "metadata_field",
                "location": "Product entity",
                "contract": "Must be a JSON-serializable dict with string keys and primitive values only",
                "description": "Custom metadata on products for extensibility",
                "example_use_case": "SEO tags",
            },
            {
                "id": "ext_webhook_channel",
                "type": "event_channel",
                "location": "Event bus",
                "contract": "Must follow CloudEvents spec with source, type, and subject fields required",
                "description": "Reserved for outbound webhook delivery",
                "example_use_case": "Notify third-party fulfillment on order creation",
            },
        ],
        "error_types": [
            {
                "name": "ProductNotFoundError",
                "code": "PRODUCT_NOT_FOUND",
                "message_template": "Product '{product_id}' not found in catalog",
                "recoverable": False,
                "http_status": 404,
            },
            {
                "name": "InsufficientStockError",
                "code": "PRODUCT_INSUFFICIENT_STOCK",
                "message_template": "Insufficient stock for product '{product_id}': requested {qty}",
                "recoverable": False,
                "http_status": 409,
            },
            {
                "name": "PaymentFailedError",
                "code": "PAYMENT_CHARGE_FAILED",
                "message_template": "Payment charge failed: {reason}",
                "recoverable": True,
                "http_status": 402,
            },
        ],
        "constants": [],
        "architectural_decisions": [],
        "assumptions": ["Stripe handles PCI compliance", "Single currency (USD)"],
        "metadata": {},
    })


# ---------------------------------------------------------------------------
# Integration: classify → generate → audit
# ---------------------------------------------------------------------------

class TestBlueprintToApprovedContract:

    def test_simple_blueprint_full_pipeline(self):
        """Full pipeline: simple blueprint → classify → generate → audit → approved."""
        blueprint = {
            "nombre": "Todo App",
            "descripcion": "Aplicación CRUD simple para gestionar tareas personales.",
            "funcionalidades": ["crear tarea", "editar tarea", "eliminar tarea"],
            "stack_sugerido": {"backend": "FastAPI"},
        }

        # Step 1: classify (real classifier)
        classifier = ProjectComplexityClassifier()
        assessment = classifier.classify(blueprint)
        assert assessment.level == ComplexityLevel.SIMPLE

        # Step 2: set up architect with mock driver returning valid contract
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)

        # Step 3: set up real auditor
        auditor = ContractAuditor(goal_tree={})

        # Step 4: run refinement loop
        loop = ContractRefinementLoop(architect, auditor, max_attempts=3)
        result = run(loop.execute(blueprint, assessment.level))

        assert result.status in ("approved", "approved_with_warnings")
        assert result.contract is not None
        assert result.contract.project_id == "proj_simple"

    def test_medium_blueprint_full_pipeline(self):
        """Full pipeline: medium blueprint → classify → generate → audit → approved."""
        blueprint = {
            "nombre": "E-Commerce",
            "descripcion": "Tienda online con carrito, pagos con Stripe y emails con SendGrid.",
            "funcionalidades": [
                "catálogo", "carrito", "checkout", "pagos", "emails",
                "admin panel", "historial pedidos",
            ],
            "stack_sugerido": {"backend": "FastAPI", "frontend": "React"},
            "integraciones": ["stripe", "sendgrid"],
        }

        classifier = ProjectComplexityClassifier()
        assessment = classifier.classify(blueprint)
        assert assessment.level == ComplexityLevel.MEDIUM

        driver = _make_driver(_medium_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=3)
        result = run(loop.execute(blueprint, assessment.level))

        assert result.status in ("approved", "approved_with_warnings")
        assert result.contract.complexity_level == "medium"

    def test_approved_contract_has_all_required_components(self):
        """Approved contract contains all MasterContract required fields."""
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        contract = result.contract
        assert len(contract.modules) >= 1
        assert len(contract.extension_points) >= 3
        assert len(contract.error_types) >= 3
        for module in contract.modules:
            assert len(module.goal_ids) >= 1
            assert len(module.interfaces) >= 1

    def test_contract_passes_consistency_validation(self):
        """All cross-references in the contract are consistent after full audit."""
        from kernel.integrity.validators.consistency import ConsistencyValidator
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        # Run consistency validator separately to confirm zero errors
        v = ConsistencyValidator()
        consistency_result = run(v.validate(result.contract))
        errors = [i for i in consistency_result.issues if i.severity == "error"]
        assert errors == [], f"Consistency errors in approved contract: {errors}"

    def test_contract_passes_naming_validation(self):
        """All naming conventions are correct in the approved contract."""
        from kernel.integrity.validators.naming import NamingValidator
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        v = NamingValidator()
        naming_result = run(v.validate(result.contract))
        errors = [i for i in naming_result.issues if i.severity == "error"]
        assert errors == [], f"Naming errors in approved contract: {errors}"

    def test_contract_passes_dependency_validation(self):
        """No circular dependencies in the approved contract."""
        from kernel.integrity.validators.dependency import DependencyValidator
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        v = DependencyValidator()
        dep_result = run(v.validate(result.contract))
        cycle_errors = [i for i in dep_result.issues if i.rule == "no_circular_dependencies"]
        assert cycle_errors == []

    def test_attempt_metadata_is_passed_to_driver(self):
        """The driver receives attempt_number and complexity metadata."""
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        run(loop.execute({}, ComplexityLevel.SIMPLE))

        _, kwargs = driver.call.call_args
        metadata = kwargs.get("metadata", {})
        assert metadata.get("attempt_number") == 1
        assert metadata.get("complexity") == "simple"
        assert metadata.get("phase") == "master_contract"

    def test_refinement_attempt_uses_correct_attempt_number(self):
        """Second attempt (refinement) passes attempt_number=2 to driver."""
        contract_json = _simple_contract_json()
        driver = _make_driver(contract_json)

        # First audit fails, second passes — so 2 driver calls
        auditor = MagicMock()
        from kernel.integrity.audit_schemas import AuditReport, Issue, ValidatorResult
        error_issue = Issue(
            severity="error", rule="test", location="x",
            description="error", suggestion="fix"
        )
        failed = AuditReport(
            contract_id="proj_simple",
            results=[ValidatorResult(validator_name="m", status="failed", issues=[error_issue])],
            overall_status="failed",
        )
        passed = AuditReport(
            contract_id="proj_simple",
            results=[ValidatorResult(validator_name="m", status="passed", issues=[])],
            overall_status="passed",
        )
        auditor.audit = AsyncMock(side_effect=[failed, passed])

        architect = Architect(driver)
        loop = ContractRefinementLoop(architect, auditor, max_attempts=3)
        run(loop.execute({}, ComplexityLevel.SIMPLE))

        # Second call (refine) should have attempt_number=2
        calls = driver.call.call_args_list
        assert len(calls) == 2
        second_metadata = calls[1][1].get("metadata", {})
        assert second_metadata.get("attempt_number") == 2
        assert second_metadata.get("action") == "refine"

    def test_full_audit_report_on_approved_contract(self):
        """AuditReport on approved contract has all 6 validators present."""
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree={})
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        report = result.attempts[-1].audit_report
        validator_names = {r.validator_name for r in report.results}
        expected = {
            "consistency_validator",
            "completeness_validator",
            "dependency_validator",
            "naming_validator",
            "extensibility_validator",
            "traceability_validator",
        }
        assert expected.issubset(validator_names)

    def test_goal_tree_integration_full_mode(self):
        """With a populated goal_tree, traceability validator runs in full mode."""
        goal_tree = {
            "children": [
                {"id": "goal_task_management"},
                {"id": "goal_data_storage"},
            ]
        }
        driver = _make_driver(_simple_contract_json())
        architect = Architect(driver)
        auditor = ContractAuditor(goal_tree=goal_tree)
        loop = ContractRefinementLoop(architect, auditor, max_attempts=1)
        result = run(loop.execute({}, ComplexityLevel.SIMPLE))

        # All goals are covered → traceability should pass
        trace = next(
            r for r in result.attempts[-1].audit_report.results
            if r.validator_name == "traceability_validator"
        )
        goal_errors = [i for i in trace.issues if i.rule == "goal_ids_valid"]
        assert goal_errors == []
