import pytest
import asyncio
from unittest.mock import MagicMock, AsyncMock
from kernel.orchestration.recursive_engine import SodaRecursiveEngine
from kernel.orchestration.copilot_loop import RetriesExhaustedError
from kernel.core.models_v2 import SodaContract, ContractStatus, ContractInterface, DynamicPersona
from kernel.intelligence.mock_generator import MockGenerator
from kernel.orchestration.retry_context import RetryContext

@pytest.mark.asyncio
async def test_anti_loop_cutoff_and_mock_injection():
    # 1. Setup mocks
    mock_gemini = AsyncMock()
    mock_ollama = AsyncMock()
    
    # Simular una respuesta de la IA que siempre es inválida (sin tags de archivo o sintaxis rota)
    mock_ollama.call.return_value = MagicMock(content="Código basura que no pasará el validador")
    
    lineup = MagicMock()
    lineup.layer4_coder = "ollama"
    
    # Crear un contrato atómico para probar
    contract = SodaContract(
        contract_id="TEST-001",
        title="Test Module",
        description="A test module",
        is_atomic=True,
        status=ContractStatus.PENDING_EXECUTION,
        interface=ContractInterface(inputs_required=[], outputs_provided=[]),
        dynamic_persona=DynamicPersona(target_role="backend", required_skills=["python"])
    )
    
    engine = SodaRecursiveEngine(
        gemini_driver=mock_gemini,
        ollama_driver=mock_ollama,
        lineup=lineup,
        stack_language="python",
        notify_fn=lambda t, m, d: print(f"[{t}] {m}")
    )
    
    # 2. Execute
    # Forzamos el error en CopilotLoopExecutor simulando que falla el validador
    # El motor recursivo debería capturar RetriesExhaustedError e inyectar un mock
    
    # Mocking PolyglotValidator to always fail
    from kernel.validators.v2.polyglot_validator import PolyglotValidator
    original_validate = PolyglotValidator.validate_code
    PolyglotValidator.validate_code = MagicMock(side_effect=ValueError("Syntax Error Inyectado para Test"))
    
    try:
        # Solo ejecutamos el audit_and_repair del motor
        files = {"test.py": "print('fail')"}
        final_files = await engine._audit_and_repair_module(contract, files)
        
        # 3. Assertions
        assert "test_001.py" in final_files
        assert "MOCK GENERATED BY SODA HEALER" in final_files["test_001.py"]
        print("SUCCESS: El motor cortó el bucle e inyectó el mock correctamente.")
        
    finally:
        # Restore validator
        PolyglotValidator.validate_code = original_validate

if __name__ == "__main__":
    asyncio.run(test_anti_loop_cutoff_and_mock_injection())
