import os
from typing import Dict, List
from kernel.core.models_v2 import SodaContract

class MockGenerator:
    """Generador determinístico de Mocks para asegurar la continuidad del pipeline SODA."""
    
    def __init__(self, stack_language: str = "python"):
        self.stack_language = stack_language

    def generate_from_contract(self, contract: SodaContract) -> Dict[str, str]:
        """Genera un archivo mock funcional basado en el contrato."""
        lang = self.stack_language.lower()
        if "python" in lang:
            return self._gen_python(contract)
        elif any(k in lang for k in ("node", "typescript", "javascript", "react", "next")):
            return self._gen_typescript(contract)
        else:
            return self._gen_generic(contract)

    def _gen_python(self, contract: SodaContract) -> Dict[str, str]:
        filename = f"{contract.contract_id.lower().replace('-', '_')}.py"
        lines = [
            f'"""MOCK GENERATED BY SODA HEALER - {contract.title}"""',
            "import logging",
            "",
            "logger = logging.getLogger(__name__)",
            "",
        ]
        
        # Generar funciones/métodos para cada salida proveída
        for output in contract.interface.outputs_provided:
            lines.append(f"def {output.name}(*args, **kwargs):")
            lines.append(f'    """Mock implementation for {output.name}."""')
            lines.append(f'    logger.warning("MOCK CALL: {output.name}")')
            # Intentar deducir un valor de retorno por defecto basado en el tipo
            ret_val = "None"
            if "List" in output.abstract_type: ret_val = "[]"
            elif "Dict" in output.abstract_type: ret_val = "{}"
            elif "int" in output.abstract_type.lower(): ret_val = "0"
            elif "bool" in output.abstract_type.lower(): ret_val = "True"
            elif "str" in output.abstract_type.lower(): ret_val = '""'
            
            lines.append(f"    return {ret_val}")
            lines.append("")

        return {filename: "\n".join(lines)}

    def _gen_typescript(self, contract: SodaContract) -> Dict[str, str]:
        filename = f"{contract.contract_id.lower()}.ts"
        lines = [
            f"/* MOCK GENERATED BY SODA HEALER - {contract.title} */",
            "",
        ]
        
        # Exportar funciones
        for output in contract.interface.outputs_provided:
            lines.append(f"export const {output.name} = (...args: any[]): any => {{")
            lines.append(f'    console.warn("MOCK CALL: {output.name}");')
            
            ret_val = "null"
            if "[]" in output.abstract_type: ret_val = "[]"
            elif "{}" in output.abstract_type: ret_val = "{}"
            elif "number" in output.abstract_type.lower(): ret_val = "0"
            elif "boolean" in output.abstract_type.lower(): ret_val = "true"
            elif "string" in output.abstract_type.lower(): ret_val = '""'
            
            lines.append(f"    return {ret_val};")
            lines.append("};")
            lines.append("")

        return {filename: "\n".join(lines)}

    def _gen_generic(self, contract: SodaContract) -> Dict[str, str]:
        filename = f"{contract.contract_id.lower()}.txt"
        content = f"MOCK FOR {contract.contract_id}\n\nOutputs required:\n"
        for o in contract.interface.outputs_provided:
            content += f"- {o.name}: {o.abstract_type}\n"
        return {filename: content}
